version: '3'

networks:
  solid_app:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: solid_app_nginx
    ports: 
      - "8000:80"
    volumes:
      - ./src:/var/www/html:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
    depends_on: 
      - php
    networks: 
      - solid_app

  php:
    build:
      context: .
      dockerfile: php.dockerfile
      target: php_base
    container_name: solid_app_php
    volumes:
      - ./src:/var/www/html:delegated
      - ./php/php.ini:/usr/local/etc/php/php.ini
    expose:
      - "9000"
    networks:
      - solid_app